version: '2'
volumes:
  frost_postgis_volume:
    external: true
services:
  web:
    image: fraunhoferiosb/frost-server:latest
    environment:
      - serviceRootUrl=https://gi3.gis.lrg.tum.de/frost
      - http_cors_enable=true
      - http_cors_allowed.origins=*
      - persistence_db_driver=org.postgresql.Driver
      - persistence_db_url=jdbc:postgresql://database:5432/sensorthings
      - persistence_db_username=sensoradmin
      - persistence_db_password=Npi6yIssTmdbrXvqKHgg
      - persistence_autoUpdateDatabase=true
      - persistence_alwaysOrderbyId=true
      - persistence_queryTimeout=240
    ports:
      - 127.0.0.1:8080:8080
      - 127.0.0.1:1883:1883
    depends_on:
      - database
    restart: always  database:
    image: postgis/postgis:11-2.5-alpine
    environment:
      - POSTGRES_DB=sensorthings
      - POSTGRES_USER=sensoradmin
      - POSTGRES_PASSWORD=Npi6yIssTmdbrXvqKHgg
    volumes:
      - frost_postgis_volume:/var/lib/postgresql/data
    restart: always
